version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    networks: 
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=leresolver"
      - "traefik.http.services.${PROJECT_NAME}-secure.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik"
    volumes:
      - ./storage:/application/storage

networks:
  traefik:
    external: true
    name: traefik